steps:

  - id: "Rodando go test"
    name: "gcr.io/cloud-builders/go:alpine"
    env: ["GOPATH=."]
    args: ['test']
  
  
  - id: "Rodando o programa"
    name: "gcr.io/cloud-builders/go:alpine"
    env: ["GOPATH=."]
    args: ['run','soma.go']
  
  
  - id: 'fazendo push da imagem para o registry'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/desafio-ci:latest', '.' ]
  
  images:
  - 'gcr.io/$PROJECT_ID/desafio-ci:latest'
  